# Generated by Django 5.0.7 on 2024-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjects', models.CharField(choices=[('Algebra', 'Algebra'), ('Geometry', 'Geometry'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=100)),
            ],
        ),
    ]
