# Generated by Django 5.2.4 on 2025-08-01 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'occupation': 'Teacher'}, related_name='subjects_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
