# Generated by Django 5.2.4 on 2025-08-03 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='subject_photos/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'teacher__isnull': False}, null=True, related_name='subjects_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
